chatbot_app/urls.py
from django.urls import path

from . import views

app_name = 'chatbot_app'
urlpatterns = [
    path('generate/', views.chatbot, name='chatbot'),
    path('clear-chats/', views.clear_chats, name='clear_chats'),
    path('', views.chatbot, name='chatbot'),
    path('get_chat_details/<int:session_id>/', views.get_chat_details, name='get_chat_details'),
    path('clear-one-chat/', views.clear_one_chat, name='clear_one_chat'),
]

chatbot_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('chatbot', include('chatbot_app.urls')),
    path('', include('chatbot_app.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name='users'
urlpatterns = [
	#include default authorization urls for our users
	path('', include('django.contrib.auth.urls')),

	#Registration page
	path('register/', views.register, name='register'),

]

chatbot_app/models.py
from django.db import models
from django.contrib.auth.models import User

#represents the chat session, which is a collection of chat messages
class ChatSession(models.Model):
    character_choice = models.CharField(max_length=255)
    media_choice = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Session with {self.character_choice} from {self.media_choice} at {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"

#represents the chat message
class ChatMessage(models.Model):
    chat_session = models.ForeignKey(ChatSession, on_delete=models.CASCADE, related_name='messages')
    user_input = models.TextField()
    generated_response = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from session {self.chat_session.id} at {self.created_at.strftime('%Y-%m-%d %H:%M:%S')}"

users/models.py
from django.db import models

# Create your models here.

chatbot_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
import google.generativeai as genai
from google.generativeai.types.generation_types import StopCandidateException
from .models import ChatSession, ChatMessage
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

@csrf_exempt
def chatbot(request):
    genai.configure(api_key='AIzaSyCKjBW9EB9XSQNwh__rARG6rc4nu8tTr6w')
    model = genai.GenerativeModel('gemini-pro')
    if request.user.is_authenticated:
        previous_chats = ChatSession.objects.filter(user=request.user)
    else:
        previous_chats = None
    if request.method == 'POST':
        
        # Start the chat with the history from the session
        chat = model.start_chat()

        user_in = request.POST.get('user_in', '')
        character_choice = request.POST.get('character_choice', '')
        media_choice = request.POST.get('media_choice', '')

        if user_in and character_choice and media_choice:
            response = None
            try:
                response = chat.send_message(f"respond to the following as if you were {character_choice} from {media_choice}: {user_in}")
            except StopCandidateException:
                response = type('', (), {})()
                response.text = "Sorry, I can't assist with that."
            print("Bot:", response.text)

            #if user is logged in, save the chat session and messages
            if request.user.is_authenticated:
                # Check if a ChatSession exists with the same character_choice and media_choice
                chat_session, created = ChatSession.objects.get_or_create(
                    character_choice=character_choice,
                    media_choice=media_choice,
                    user = request.user
                )

                # Create a new ChatMessage linked to the found or created ChatSession
                ChatMessage.objects.create(
                    chat_session=chat_session,
                    user_input=user_in,
                    generated_response=response.text
                )

            context = {
                'previous_chats': previous_chats,
                'character_choice': character_choice,
                'media_choice': media_choice,
                'user_in': user_in,
                'generated_text': response.text
            }
            return JsonResponse({
                'character_choice': character_choice,
                'media': media_choice,
                'user_in': user_in,
                'generated_text': response.text
                })
                
        else:
            return HttpResponse("Please provide user_in, character_choice, and media_choice as GET parameters.")
    else:
        context = {'previous_chats': previous_chats}
        return render(request, 'chatbot_app/generate_text.html', context)


@login_required
def clear_chats(request):
    if request.method == 'POST' and 'clear_chats' in request.POST:
        ChatSession.objects.all().delete()
    return HttpResponseRedirect(reverse('chatbot'))

@login_required
def clear_one_chat(request):
    if request.method == 'POST' and 'clear_one_chat' in request.POST:
        session_id = request.POST.get('session_id', '')
        if session_id:
            ChatSession.objects.filter(id=session_id).delete()
    return HttpResponseRedirect(reverse('chatbot'))

def get_chat_details(request, session_id):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        session = get_object_or_404(ChatSession, id=session_id)
        # Fetch user inputs and generated responses separately
        user_inputs = session.messages.all().order_by('created_at').values_list('user_input', flat=True)
        generated_responses = session.messages.all().order_by('created_at').values_list('generated_response', flat=True)
        
        # Interleave the two lists and flatten them
        messages = [item for pair in zip(user_inputs, generated_responses) for item in pair if item]
        
        response_data = {
        'character_choice': session.character_choice,
        'media_choice': session.media_choice,
        'messages': messages,
    }
        return JsonResponse(response_data)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
	"""Register a new user."""
	if request.method != 'POST':
 		# Display blank registration form.
		form = UserCreationForm()
	else:
 		# Process completed form.
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
 			# Log the user in and then redirect to home page.
			login(request, new_user)
			return redirect('chatbot_app:chatbot')
	# Display a blank or invalid form.
	context = {'form': form}
	return render(request, 'registration/register.html', context)

chatbot_app/templates/chatbot_app/chat_session_details.html
{% for message in messages %}
    <div class="chat-message">
        <p><strong>User Input:</strong> {{ message.user_input }}</p>
        <p><strong>Generated Response:</strong> {{ message.generated_response }}</p>
    </div>
{% endfor %}

chatbot_app/templates/chatbot_app/generate_text.html
{% extends "chatbot_app/master.html" %}
{% block title %}
   AI Roleplayer
{% endblock %}
{% block content %}
<div class="page-title">
<h2>AI Roleplayer Chatbot</h2>
<h3>Speak to your favorite character from any franchise</h3>
<!--add a space-->
{% if user.is_authenticated %}
			<li class="nav-item register-link">
				<span class="navbar-text">Hello, {{ user.username }}.</span>
			</li>
			<li class="nav-item login-link">
				<form action="{% url 'users:logout' %}" method="post">
					{% csrf_token %}
					<button class="btn btn-primary btn-login" type="submit">Log out</button>
				</form>
			</li>
		{% else %}
			<li class="nav-item register-link">
				<a class = "btn btn-primary btn-register" href="{% url 'users:register' %}">Register</a>
			</li>
			<li class="nav-item login-link">
				<a class = "btn btn-primary btn-login" href="{% url 'users:login' %}">Log in</a>
			</li>
		{% endif %}
</div>

<button id="hamburger">
    <span class="hamburger__line"></span>
    <span class="hamburger__line"></span>
    <span class="hamburger__line"></span>
</button>

<div id="previous-chats" style="display:none;">
    <form method="post" action="{% url 'chatbot_app:clear_chats' %}">
        {% csrf_token %}
        <!--<button type="submit" name="clear_chats" value="1">Clear All Chats</button>-->
    </form>
    
    {% for chat in previous_chats %}
    <div class="previous-chat">
        <div class="d-flex align-items-center">
            <!-- Display only the chats the user created if they're logged in -->
            {% if user.is_authenticated %}
                <button class="prev-chat-label btn btn-info" data-session-id="{{ chat.id }}">
                    <strong>{{ chat.character_choice }}</strong>
                </button>
                <!-- Updated part: Form for deleting a single chat -->
                <form method="post" action="{% url 'chatbot_app:clear_one_chat' %}" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="session_id" value="{{ chat.id }}">
                    <button type="submit" class="btn btn-secondary ml-2" name="clear_one_chat" value="1">X</button>
                </form>
            {% endif %}
        </div>
    </div>
    {% empty %}
    <p>No previous chats found.</p>
{% endfor %}

</div>
<div class="container">
    <div class="chatbox">
        <div class="chatbox__support">
            <div class="chatbox__header">
                
                <div class="chatbox__content--header">
                    
                    <p class="chatbox__description--header"></p>
                    <form method="post" id="chat" action="{% url 'chatbot_app:chatbot' %}">
                        <!-- This token ensures that the request is coming from the same site. -->
                        {% csrf_token %}
                        
                        <!-- Input for character choice -->
                        <div class="choices">
                        <label for="character_choice">Enter the character you want to speak with:</label><br>
                        <textarea name="character_choice" rows = 1>{{ request.POST.character_choice }}</textarea><br><br>
                        
                        <!-- Input for associated media -->
                        <label for="media">Enter the name of the movie/book/etc The character is from:</label><br>
                        <textarea name="media_choice" rows = 1>{{ request.POST.media_choice }}</textarea><br><br>
                        </div>
                        <div class="chatbox__messages mb-3">
                            <div></div>
                        </div>
                        <!-- User input -->
                        <div class="chatbox__footer">
                            <textarea name="user_in" placeholder="Write a message...">{{ request.POST.user_in }}</textarea>
                            <div class="input-group-append">
                                <button class="btn btn-primary send__button">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
        <div class="chatbox__button">
            
        </div>
    </div>

    <button class = "btn btn-primary new-chat-btn" id="new-chat-btn">New Chat</button>

</div>

<div class="response">
    <!-- Display the generated text 
{% if generated_text %}
    <h3><span>{{ request.POST.character_choice }}</span> Says:</h3>
    <p>{{ generated_text }}</p>
{% endif %}
-->
</div>
<script>
    class Chatbox {
        constructor() {
            this.args = {
                openButton: document.querySelector('.chatbox__button'),
                chatBox: document.querySelector('.chatbox__support'),
                sendButton: document.querySelector('.send__button')
            }
    
            this.state = false;
            this.messages = [];
        }
    
        display() {
            const {openButton, chatBox, sendButton} = this.args;
    
            openButton.addEventListener('click', () => this.toggleState(chatBox))
                
            const node = chatBox.querySelector('textarea[name="user_in"]');
            node.addEventListener("keyup", ({key}) => {
                if (key === "Enter") {
                    this.sendMessage(chatBox)
                }
            })

            // Attach form submission event listener here
            document.querySelector('#chat').addEventListener('submit', (e) => {
                e.preventDefault();
                this.sendMessage(chatBox);
            });
    
            this.bindPreviousChatButtons();
        }
    
        bindPreviousChatButtons() {
            document.querySelectorAll('.prev-chat-label').forEach(element => {
                element.addEventListener('click', () => {
                    const sessionId = element.getAttribute('data-session-id');
                    fetch(`/get_chat_details/${sessionId}/`, { // Adjust the URL as needed
                        method: 'GET',
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest',
                            'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                        },
                    })
                    .then(response => response.json())
                    .then(data => {

                        document.querySelector('textarea[name="character_choice"]').value = data.character_choice;
                        document.querySelector('textarea[name="media_choice"]').value = data.media_choice;

                        // Modify this part to alternate names between "User" and "Sam"
                        this.messages = data.messages.map((msg, index) => {
                            // Determine the name based on the index being odd or even
                            const name = index % 2 === 0 ? "User" : "Sam";
                            return { name: name, message: msg };
                        });
                        this.updateChatText(this.args.chatBox);
                    })
                    .catch(error => console.error('Error:', error));
                });
            });
        }
    
        toggleState(chatbox) {
            this.state = !this.state;
    
            // show or hides the box
            if(this.state) {
                chatbox.classList.add('chatbox--active')
            } else {
                chatbox.classList.remove('chatbox--active')
            }
        }
        sendMessage(chatbox) {
            // Get the data from the character and media choice form
            var characterChoice = document.querySelector('.choices textarea[name="character_choice"]').value;
            var mediaChoice = document.querySelector('.choices textarea[name="media_choice"]').value;
    
            // Get the data from the user input form
            var userIn = chatbox.querySelector('textarea[name="user_in"]').value;
            let text1 = userIn
            if (text1 === "") {
                return;
            }
            let msg1 = { name: "User", message: text1 }
            chatbox.querySelector('textarea[name="user_in"]').value = '';
            this.messages.push(msg1);
            this.updateChatText(chatbox);

            // Create a FormData object and append all the data
            var formData = new FormData();
            formData.append('character_choice', characterChoice);
            formData.append('media_choice', mediaChoice);
            formData.append('user_in', userIn);
    
            // Send the form data to the server
            fetch(document.querySelector('#chat').action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': document.querySelector('#chat [name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => response.json())
            .then(response => {
                console.log(response);
                let msg2 = { name: "Sam", message: response.generated_text };
                this.messages.push(msg2);
                this.updateChatText(chatbox);
                textField.value = ''
            })
            .catch(error => console.error('Error:', error));
            //this.updateChatText(chatbox)
            //textField.value = ''
        }

        updateChatText(chatbox) {
            var html = '';
            this.messages.slice().forEach(function(item, index) {
                if (item.name === "Sam")
                {
                    html += '<div class="alert alert-primary messages__item messages__item--visitor">' + item.message + '</div>'
                }
                else
                {
                    html += '<div class="alert alert-secondary messages__item messages__item--operator">' + item.message + '</div>'
                }
            });
        
            const chatmessage = chatbox.querySelector('.chatbox__messages');
            chatmessage.innerHTML = html;
        }
    }
const chatbox = new Chatbox();
chatbox.display();

document.getElementById('new-chat-btn').addEventListener('click', function() {
    window.location.reload();
});
document.getElementById('hamburger').addEventListener('click', function() {
    var previousChats = document.getElementById('previous-chats');
    if (previousChats.style.display === "none") {
        previousChats.style.display = "block";
    } else {
        previousChats.style.display = "none";
    }
});
</script>
{% endblock %}

chatbot_app/templates/chatbot_app/master.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  
  <!--   -->
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">  
  
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

chatbot_app/templates/generate_text.html
{% extends "master.html" %}
{% block title %}
   AI Roleplayer
{% endblock %}
{% block content %}
<div class="page-title">
<h2>AI Roleplayer Chatbot</h2>
<h3>Speak to your favorite character from any franchise</h3>
</div>
<div class="container">
    <div class="chatbox">
        <div class="chatbox__support">
            <div class="chatbox__header">
                
                <div class="chatbox__content--header">
                    <h4 class="chatbox__heading--header">ChatBot</h4>
                    <p class="chatbox__description--header"></p>
                    <form method="post" id="chat" action="{% url 'chatbot' %}">
                        <!-- This token ensures that the request is coming from the same site. -->
                        {% csrf_token %}
                        
                        <!-- Input for character choice -->
                        <div class="choices">
                        <label for="character_choice">Enter the character you want to speak with:</label><br>
                        <textarea name="character_choice" rows = 1>{{ request.POST.character_choice }}</textarea><br><br>
                        
                        <!-- Input for associated media -->
                        <label for="media">Enter the name of the movie/book/etc The character is from:</label><br>
                        <textarea name="media_choice" rows = 1>{{ request.POST.media_choice }}</textarea><br><br>
                        </div>
                        <div class="chatbox__messages mb-3">
                            <div></div>
                        </div>
                        <!-- User input -->
                        <div class="chatbox__footer">
                            <textarea name="user_in" placeholder="Write a message...">{{ request.POST.user_in }}</textarea>
                            <div class="input-group-append">
                                <button class="btn btn-primary send__button">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
        <div class="chatbox__button">
            
        </div>
    </div>
</div>
<div class="response">
    <!-- Display the generated text 
{% if generated_text %}
    <h3><span>{{ request.POST.character_choice }}</span> Says:</h3>
    <p>{{ generated_text }}</p>
{% endif %}
-->
</div>
<script>
    class Chatbox {
        constructor() {
            this.args = {
                openButton: document.querySelector('.chatbox__button'),
                chatBox: document.querySelector('.chatbox__support'),
                sendButton: document.querySelector('.send__button')
            }
    
            this.state = false;
            this.messages = [];
        }
    
        display() {
            const {openButton, chatBox, sendButton} = this.args;
    
            openButton.addEventListener('click', () => this.toggleState(chatBox))
    
            //sendButton.addEventListener('click', () => this.sendMessage(chatBox))
    
            const node = chatBox.querySelector('textarea[name="user_in"]');
            node.addEventListener("keyup", ({key}) => {
                if (key === "Enter") {
                    this.sendMessage(chatBox)
                }
            })
    
            // Attach form submission event listener here
            document.querySelector('#chat').addEventListener('submit', (e) => {
                e.preventDefault();
                this.sendMessage(chatBox);
            });
        }
    
        toggleState(chatbox) {
            this.state = !this.state;
    
            // show or hides the box
            if(this.state) {
                chatbox.classList.add('chatbox--active')
            } else {
                chatbox.classList.remove('chatbox--active')
            }
        }
        sendMessage(chatbox) {
            // Get the data from the character and media choice form
            var characterChoice = document.querySelector('.choices textarea[name="character_choice"]').value;
            var mediaChoice = document.querySelector('.choices textarea[name="media_choice"]').value;
    
            // Get the data from the user input form
            var userIn = chatbox.querySelector('textarea[name="user_in"]').value;
            let text1 = userIn
            if (text1 === "") {
                return;
            }
            let msg1 = { name: "User", message: text1 }
            chatbox.querySelector('textarea[name="user_in"]').value = '';
            this.messages.push(msg1);
            this.updateChatText(chatbox);

            // Create a FormData object and append all the data
            var formData = new FormData();
            formData.append('character_choice', characterChoice);
            formData.append('media_choice', mediaChoice);
            formData.append('user_in', userIn);
    
            // Send the form data to the server
            fetch(document.querySelector('#chat').action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': document.querySelector('#chat [name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => response.json())
            .then(response => {
                console.log(response);
                let msg2 = { name: "Sam", message: response.generated_text };
                this.messages.push(msg2);
                this.updateChatText(chatbox);
                textField.value = ''
            })
            .catch(error => console.error('Error:', error));
            //this.updateChatText(chatbox)
            //textField.value = ''
        }

        updateChatText(chatbox) {
            var html = '';
            this.messages.slice().forEach(function(item, index) {
                if (item.name === "Sam")
                {
                    html += '<div class="alert alert-primary messages__item messages__item--visitor">' + item.message + '</div>'
                }
                else
                {
                    html += '<div class="alert alert-secondary messages__item messages__item--operator">' + item.message + '</div>'
                }
            });
        
            const chatmessage = chatbox.querySelector('.chatbox__messages');
            chatmessage.innerHTML = html;
        }
    }
const chatbox = new Chatbox();
chatbox.display();
</script>
{% endblock %}